import type { Metadata } from "next";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import { Button } from "@/components/ui/button";
import "./globals.css";
import "katex/dist/katex.min.css";
import { dark } from "@clerk/themes";
import StoreProvider from "./storeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <ClerkProvider>
        <html lang="en" className="scroll-smooth">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}
          >
            <header className="sticky top-0 z-50 bg-black border-b border-white/10">
              <div className="mx-auto flex h-16 w-full items-center justify-end gap-3 px-4 sm:px-8">
                <SignedIn>
                  <UserButton
                    appearance={{
                      theme: dark,
                    }}
                  />
                </SignedIn>
              </div>
            </header>
            {children}
          </body>
        </html>
      </ClerkProvider>
    </StoreProvider>
  );
}
